version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    networks:
      - backend
    depends_on:
      - api
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/packages/frontend/node_modules
    restart: unless-stopped
    ports:
      - 3000:3000
  api:
    container_name: api
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/packages/api/node_modules
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 8000:8000

networks:
  backend:
    driver: bridge

